ENV["VAGRANT_NO_PARALLEL"] = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider :libvirt
  config.vm.hostname = "isapavadS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider "libvirt" do |lv|
    lv.memory = 2048
    lv.cpus = 2
    end

  config.vm.provision "shell", path: "scripts/server.sh"

end
