ENV["VAGRANT_NO_PARALLEL"] = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.provider :libvirt
  config.vm.hostname = "isapavadS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provider "libvirt" do |lv|
    lv.driver = "qemu"
    lv.cpu_mode = "custom"
    lv.cpu_model = "qemu64"
    lv.memory = 2048
    lv.cpus = 2
    lv.graphics_type = "none"
    lv.video_type = "none"
  end

  config.vm.provision "shell", path: "scripts/network.sh"
  
  config.vm.provision "shell", path: "scripts/server.sh"

end
