ENV["VAGRANT_NO_PARALLEL"] = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider :libvirt

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.define "isapavadS" do |server|
    server.vm.hostname = "isapavadS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "isapavadSW" do |worker|
    worker.vm.hostname = "isapavadSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    worker.trigger.before :up do |trigger|
      trigger.info = "Waiting for K3s server token before starting worker"
      trigger.run = {
        inline: "bash scripts/wait-token.sh"
      }
    end

    worker.vm.provision "shell", path: "scripts/agent.sh"
  end
end
